server:
  port: 9000


spring:
  application:
    name: gateway

#指定注册中心地址
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

#自定义路由
zuul:
  routes:
    feign-service: /apigateway-order/**
    product-service: /apigateway-product/**
  #过滤路径
  ignored-patterns: /*-service/**
  #过滤服务
#  ignored-services: product-service