server:
  port: 8791

#指定注册中心地址
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

#服务名称
spring:
  application:
    name: feign-service
  redis:
    database: 0
    host: 10.37.129.3
    port: 6379
    timeout: 2000

#自定义负载均衡
product-service:
  ribbon:
    NFLoadBalancerRuleClassName: com.netflix.loadbalancer.RandomRule

#修改调用超时时间
feign:
  client:
    config:
      default:
        connectTimeout: 2000
        readTimeout: 2000
  hystrix:
    enabled: true

#debug日志级别
logging:
  level:
    com:
      mouse:
        feign:
          service:
            ClientProductService: debug

#hystrix超时 策略
hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 4000